### ISSUE TITLE
Private repository dependency

### ISSUE THREAD

**Issue by metalmatze** [lertify/lastfm-api#1]
Could not fetch https://api.github.com/repos/Jurager/lastfm-api/zipball/3b882763eb22a0e4ebc2cb3106ac2bf2aad2d1c0, enter your GitHub credentials to access private repos
The credentials will be swapped for an OAuth token stored in /home/metalmatze/.composer/config.json, your password will not be stored
To revoke access to this token you can visit https://github.com/settings/applications

**Comment by jeserkin** [comment]
Sorry. Don't understand the question. Could you elaborate on it or rephrase it?

**Comment by metalmatze** [comment]
No problem.
When I use composer to grab your files it tells me to provide credentials to the private repository on https://github.com/Jurager/lastfm-api.
There has to be some dependency.

**Comment by jeserkin** [comment]
Well, all of them are present in `require` in `composer.json`

**Comment by metalmatze** [comment]
Yep, but somehow composer always wants to fetch the private repo from above...

**Comment by jeserkin** [comment]
Odd. I can't seem to open the link you provided to forked repo. Have you removed it? If not, then there might be an issue with it. If so, then try to fork again if there where no commits done by you. Also I have to warn you. There is a bit resturing on the way for iternals of api methods and structure of data classes.
